reviews/urls.py
from django.conf.urls import url

from . import views

app_name = 'reviews'

urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url(r'^wine$', views.wine_list, name='wine_list'),
    # ex: /wine/5/
    url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    url(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    # ex: /review/user - get reviews for the logged user
    url(r'^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    # ex: /review/user - get reviews for the user passed in the url
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    # ex: /recommendation - get wine recommendations for the logged user
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
    url(r'^ncf_recommendation/$', views.ncf_users_recommendation_list, name='ncf_users_recommendation_list'),
    # ex: /about
    url(r'^about/$', views.about, name='about')
]

winerama/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include(('reviews.urls', 'reviews'), namespace="reviews")),
    url(r'^reviews/', include(('reviews.urls', 'reviews'), namespace="reviews")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    # imported all the mappings from django.contrib.auth.urls
    url(r'^accounts/', include(('django.contrib.auth.urls', 'auth'), namespace="auth")),
]

reviews/models.py
from django.db import models
import numpy as np
from django.contrib.auth.models import User


class Wine(models.Model):
    name = models.CharField(max_length=200)
    genres = models.CharField(max_length=200, default='unspecified')
    poster_path = models.CharField(max_length=500, default='unspecified')
    
    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        mean_ratings = np.mean(list(all_ratings))
        return mean_ratings
        
    def __unicode__(self):
        return self.name


class Fake(models.Model):
    actual_id = models.IntegerField(
        default=max(list(User.objects.values_list('id', flat = True))) + 1)

    fake_id = models.AutoField(primary_key=True, default=User.objects.count())

class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    wine = models.ForeignKey(Wine,
                             on_delete=models.CASCADE,)
    pub_date = models.DateTimeField('date published')
    user_id = models.IntegerField(default=User.objects.count())
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)
    

class Cluster(models.Model):

    # Bir küme için bir ad ve kullanıcı listesi saklar
    # Bu ManyToManyField ürününü kullanarak kullanıcıların birden fazla kümeye ait olmalarını sağlamak için kapıyı açık bırakıyoruz.
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    # Ayrıca tüm üye kullanıcı adlarını get_memebers almak için bir yöntem tanımlar
    def get_members(self):
        return "\n".join([u.username for u in self.users.all()])

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Review, Wine, Cluster, Fake
from .forms import ReviewForm
from .suggestions import svd_recommendations, recommend_movies
from .ncf import load_model, update_model, get_model
from .fetch_videos import fetch
import datetime, sys
import pandas as pd
import numpy as np
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import tensorflow as tf

from django.contrib.auth.decorators import login_required

updated_model_init = False
previous_user = None

def about(request):
    return render(request, 'reviews/about.html')

def review_list(request):
    global updated_model_init
    global previous_user
    latest_review_list = Review.objects.order_by('-pub_date')[:12]
    context = {
        'latest_review_list':latest_review_list,
        'temp1': 'Not Found',
        'temp2': 'https://image.tmdb.org/t/p/w500None'
    }
    print(latest_review_list)

    if request.user.is_authenticated == True:
        user_id = request.user.id
        try:
            Fake.objects.get(actual_id=user_id)
        except:
            fake = Fake()
            fake.actual_id = user_id
            fake.fake_id = User.objects.count()
            fake.save()
            print(fake.actual_id, fake.fake_id, '---------the--end')

    try:
        user_id = request.user.id
        if previous_user != user_id:
            updated_model_init = False
            previous_user = user_id
        temp = User.objects.get(id=user_id)
        print(temp.last_login.time().strftime("%H:%M:%S"), temp.date_joined.time().strftime("%H:%M:%S"))
        if (not updated_model_init) and (temp.last_login.date() == temp.date_joined.date()):
            if abs(int(temp.last_login.time().strftime("%M")) - int(temp.date_joined.time().strftime("%M"))) < 2:
                update_model(user_id, True)
                updated_model_init = True
    except:
        None

    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def wine_list(request):
    wine_list = Wine.objects.order_by('-name')
    #wine_list = fetch(wine_list)
    
    page = request.GET.get('page', 1)
    paginator = Paginator(wine_list, 12)

    try:
        wine_list = paginator.page(page)
    except PageNotAnInteger:
        wine_list = paginator.page(1)
    except EmptyPage:
        wine_list = paginator.page(paginator.num_pages)

    # Geçerli sayfanın dizinini alır
    index = wine_list.number - 1
    # Bu değer, sayfalarınızın maksimum dizinidir, bu nedenle son sayfa - 1
    max_index = len(paginator.page_range)
    # 7 aralığı istiyorsan, listeyi nerede keseceğini hesaplar
    start_index = index - 3 if index >= 3 else 0
    end_index = index + 3 if index <= max_index - 3 else max_index
    # Yeni sayfa aralığını alır. Django son sürümlerinde page_range returns
    # bir yineleyici. Böylece diliminizi tekrar mümkün kılmak için listeye aktarır.
    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'wine_list':wine_list,
        'page_range': page_range, 
        'temp1': 'Not Found',
        'temp2': 'https://image.tmdb.org/t/p/w500None'
     }

    return render(request, 'reviews/wine_list.html', context)


def wine_detail(request, wine_id):
    movie_obj = get_object_or_404(Wine, pk=wine_id)
    movie_info = fetch(movie_obj)

    form = ReviewForm()

    return render(
        request, 
        'reviews/wine_detail.html',
        {'wine': movie_obj,
         'form': form,
         'movie_info': movie_info,
         'temp1': 'Not Found', 
         'temp2': 'https://image.tmdb.org/t/p/w500None'
         })


# erişimi add_review görünümümüzle sınırlandırır, böylece yalnızca oturum açmış kullanıcılar kullanabilir.

@login_required
def add_review(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        # user_name = form.cleaned_data['user_name']

        # İstek nesnesinin aktif kullanıcıya referansı var
        # ihtiyaç duyduğumuzda kullanabileceğimiz bir kullanıcı adı alanı var.
        user_name = request.user.username
        user_id = request.user.id

        print('User id: {}\t-------\t User name: {}'.format(user_id, user_name))

        try:
            # Bu filmin bu kullanıcı tarafından incelemesi zaten varsa, derecelendirmeyi günceller
            obj = Review.objects.get(wine__id=wine.id, user_id=user_id)
            obj, created = Review.objects.update_or_create(
                user_id=user_id, wine__id=wine.id,
                defaults={'rating':rating,
                         'comment': comment,
                         'pub_date': datetime.datetime.now()})
        except:
            # aksi takdirde yeni bir inceleme kaydeder
            review = Review()
            review.wine = wine
            review.user_id = user_id
            review.user_name = user_name
            review.rating = rating
            review.comment = comment
            review.pub_date = datetime.datetime.now()
            review.save()

        update_model(request.user.id)

        # Başarılı bir şekilde işlem yaptıktan sonra her zaman bir HttpResponse Redirect döndür
        # POST verileri. Bu, örneğin, verilerin iki kez gönderilmesini önler.
        # kullanıcı Geri düğmesine basar.
        return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))
    
    return render(
        request, 
        'reviews/wine_detail.html', 
        {'wine': wine, 'form': form, 'username': user_name}
        )

@login_required
def user_review_list(request, username=None):
    global updated_model_init
    global previous_user
    user_id = request.user.id
    if not username:
        username = request.user.username

    try:
        update_Fake = Fake.objects.get(actual_id=user_id)
    except:
        fake = Fake()
        fake.actual_id = user_id
        fake.fake_id = User.objects.count()
        fake.save()

    print((Fake.objects.get(actual_id=user_id)).fake_id, ': fake id\t--------')
    print(request.user.username, '-----------', request.user.id)

    if previous_user != user_id:
        updated_model_init = False
        previous_user = user_id
    temp = User.objects.get(id=user_id)
    print(temp.last_login.time().strftime("%H:%M:%S"), temp.date_joined.time().strftime("%H:%M:%S"))
    if (not updated_model_init) and (temp.last_login.date() == temp.date_joined.date()):
        if abs(int(temp.last_login.time().strftime("%M")) - int(temp.date_joined.time().strftime("%M"))) < 2:
            update_model(user_id, True)
            updated_model_init = True

    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list':latest_review_list, 'username':username}
    return render(request, 'reviews/user_review_list.html', context)

# kullanıcılara önerilecekleri temsil eder (bu durumda filmler)
@login_required
def user_recommendation_list(request):
    
    temp = svd_recommendations(request.user.id)
    error = temp[0]
    preds = (temp[1])[:10]
    print(preds)
    wine_list = Wine.objects.filter(id__in=preds.MovieID.values)

    return render(
        request, 
        'reviews/user_recommendation_list.html', 
        {'username': request.user.username, 'wine_list': wine_list, 'error': error}
        )

#already_trained = False

@login_required
def ncf_users_recommendation_list(request):

    #global already_trained

    print("Predicting")

    user_reviews = Review.objects.filter(user_name=request.user.username).prefetch_related('wine')

    # 2. derecelendirmelerden, kullanıcının derecelendirdiği bir dizi film kimliği edinir
    user_reviews_wine_ids = set(map(lambda x: x.wine.id, user_reviews))
    # daha sonra önceki kimlikleri hariç bir film kimlikleri alır
    wine_list = Wine.objects.exclude(id__in=user_reviews_wine_ids)
    
    res = []
    user_id = Fake.objects.get(actual_id = request.user.id).fake_id


    with tf.Session():
        if (len(user_reviews_wine_ids) != 0):
            model = load_model()
            model.load_weights("./model.h5")
            for row in wine_list:
                res.append([row.id, 
                    model.predict(
                        [np.array([user_id]), np.array([row.id])]
                    )[0][0]]
                )
            res = pd.DataFrame(res, columns=['movieid', 'prediction'])
        else:
            #update model
            #update_model(user_id, True)
            #model = load_model()
            #model.load_weights("./model.h5")
            #for row in wine_list:
            #    res.append([row.id, model.predict(
            #        [np.array([user_id]), np.array([row.id])]
            #        )[0][0]])

            # wine.review_set.count

            temp = pd.DataFrame(list(Wine.objects.all()), columns=['wine'])
            res = pd.DataFrame(
                [[i.average_rating(), i.review_set.count(), i.id] for i in temp.wine.values.tolist()],
                columns=['prediction', 'count', 'movieid']
                )

            res = res.sort_values(by='count', ascending=False)[:10]

            #print(res.head())

    res = res.sort_values(by='prediction', ascending=False)

    #print(res.head())

    temp = res.movieid.values[:10]

    wine_list = Wine.objects.filter(id__in=temp)

    return render(
        request, 
        'reviews/ncf_users_recommendation_list.html', 
        {'username': request.user.username,'wine_list': wine_list}
    )

reviews/templates/reviews/about.html
{% extends 'base.html' %}

{% block title %}
{% load static %}
<h2 class="text-center" id="navMargin">Hakkımızda</h2>
{% endblock %}

{% block content %}

<div class="container-fluid" style="padding: 30px;">
	<p class="lead text-justify" style="font-size: 16px;">
		<img class="img-responsive" src="{% static '/pencil.png' %}" alt="@" style="height: 100%; padding-left: 10px; padding-bottom: 10px; float: right;">
		Bu çalışma Uyarlanabilir Sistemler dersi bitirme ödevi için geliştirilmiştit. Çalışmada amaç Akıllı Öğrenme Platformu aracılığıyla öğrenenlere kullanıcı alanlarına göre İşbirlikli Filtreleme teknikleri kullanılarak önerilerde bulunmaktır.
		<br>
        Tekil Değer Ayrışımı, bilim ve teknolojinin çeşitli alanlarında kullanılan bir matris faktoring yöntemidir. Ayrıca, son zamanlarda makine öğrenmesi, veri madenciliği ve teorik bilgisayar bilimlerindeki büyük gelişmeler nedeniyle, SVD giderek daha önemli hale gelmiştir.<br>
		<em>Matris Faktörleşmesi: Bir matrisin bir matris ürününe temsilidir.</em>
		<br><br>
		<strong>SVD arkasındaki matematiksel yapı</strong><br>
		Bir mxn matrisi (M) için, M formunun bir tekil değer ayrışımı vardır:
		M = UΣV<sup>T</sup><br>
		Bunlar
		<ul>
			<li>U, bir mx k birim matrikstir. (sol tekil vektör)</li>
			<li>Σ, negatif olmayan reel sayıları olan bir kx k köşegen matrisidir.</li>
			<li>V, kxn üniter bir matristir. (sağ tekil vektör)</li>
			<li>V<sup>T</sup> "n × n" üniter matrisin eşlenik devridir.</li>
			<li>Σ'nın köşegen değerleri, M'nin Tekil değerleri (tam olarak 'k') olarak bilinir.</li>
		</ul>
		<em>Conjugate Transpose</em>: Bir matrisin eşlenik devri, her eleman için satır ve sütun indeksini değiştirir.<br>
		<em>Kimlik matrisi</em>: Ana köşegenin tüm öğelerinin sıfır olduğu ve tüm diğer öğelerin sıfır olduğu kare bir matristir.<br>
		<em>Diyagonal matris</em>: Ana köşegen dışındaki girişlerin sıfır olduğu bir matristir.<br>
		<em>Üniter matris</em>: Konjugat transpoze olan matrisler de tersidir, bu UU<sup>T</sup>=I.<br>
		<em>Tekil Değerler</em>: Temel olarak, X'in bir matris olduğu "XX <sup> T </sup>" özdeğerlerinin karekökü anlamına gelir.
	</p>
	<p class="lead text-justify" style="font-size: 16px;">
		<br>
        <strong> Boyutsal küçülme </strong> <br>
        Veri kümelerini temsil etmenin yaygın bir yolu, bir öznitelikteki vektörler gibidir. Örneğin, her boyutun bir film olmasına izin verirsek, kullanıcıları nokta olarak temsil edebiliriz. Bunu üçten fazla boyutta görselleştirememize rağmen, fikir herhangi bir sayıda boyut için işe yarar.
        Bu ortamda sorulması gereken doğal bir soru, verileri temsil etmemiz gereken boyut sayısını azaltmanın mümkün olup olmadığıdır. Örneğin, Matematik I’i seven her kullanıcı Matematik II'den hoşlanıyorsa, toplayıcı bir ders veya özellik oluşturmak için onları bir araya toplayabiliriz. Daha sonra iki dersi, tek tek filmler yerine farklı özellikler için derecelendirmelerine bakarak karşılaştırabiliriz. <br>
        Bunu yapmak istememizin birkaç nedeni var. Birincisi ölçeklenebilirlik. 17.000 ders içeren bir veri kümemiz varsa, her kullanıcı 17.000 koordinattan oluşan bir vektördür ve bu, kullanıcıları nispeten yavaş ve bellek yoğun biçimde depolamayı ve karşılaştırmayı sağlar. Bununla birlikte, daha az sayıda boyut kullanmanın aslında tahmin doğruluğunu iyileştirebileceği ortaya çıktı. Örneğin, ikisinin de matematik seven iki kullanıcımız olduğunu varsayalım. Bir kullanıcı <em> Matematik I </em> 'i ve diğeri <em> Lineer Cebir </em>' e yüksek puan verdiyse, kullanıcıların benzer olduğunu söylemek mantıklı olur. Bununla birlikte, kullanıcıları ayrı ayrı derslere göre karşılaştırırsak, yalnızca her iki kullanıcının da derecelendirdiği dersler benzerliklerini etkiler. Bu aşırı bir örnektir, ancak mutlaka karşılaştırılması gereken çeşitli sınıflar olduğunu hayal edebiliyorum. <br> <br>
        <b> Boyutluluk Azaltma ve Tekil Değer Ayrışması: - </b> <br>
        "Σ" matrisi, M matrisinin tekil değerlerini içeren çapraz bir matristir. Tam olarak 'k' tekil değerleri vardır, burada k, M'nin rütbesidir. Bir matrisin <em> sırası </em> sayıdır Matris içinde doğrusal olarak bağımsız satır veya sütunların listesi. Uzaydaki diğer herhangi bir vektörün toplamı veya skalar katı olarak yazılamıyorsa, iki vektörün doğrusal olarak bağımsız olduğunu hatırlayın. Doğrusal bağımsızlığın bir şekilde elde etmeye çalıştığımız özellik veya aglomeratif madde kavramını yakaladığını gözlemleyin. Önceki örneğimize geri dönmek gerekirse, <em> Matematik I </em> 'i seven her kullanıcı Matematik II'yi de sevdiyse, iki ders vektörü doğrusal olarak bağımlı olacaktır ve yalnızca bir taneye katkısı olacaktır. <br>
        Ancak daha fazlasını yapabiliriz. Birini beğenen çoğu diğerinden de hoşlanıyorsa, dersleri gerçekten karşılaştırmak istiyoruz. Bunu başarmak için ilk "r" tekil değerlerini "r" <"k" olan "Σ" da tutabiliriz. Bu, bize X'e en iyi rütbe yaklaşımını verecek ve böylece orijinal alanımızın boyutsallığını etkili bir şekilde azaltacaktır. <br>
        Böylece, "Σ" şimdi "rxr" boyutuna sahip olacaktır. </p>
	<blockquote style="padding: 30px;">
		<p class="text-muted lead">Kaynakça: <small>
			<a href="http://www.cs.carleton.edu/cs_comps/0607/recommend/recommender/svd.html" target="_blank">
				Dimensionality Reduction and the Singular Value Decomposition
			</a></small></p>
	</blockquote>
</div>

{% endblock %}

reviews/templates/reviews/ncf_users_recommendation_list.html
{% extends 'reviews/wine_list.html' %}

{% block title %}
<h2 class="text-center" id="navMargin">En Popüler 10 İçerik</h2>
{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2 id="navMargin"><a href="{% url 'reviews:wine_detail' review.wine.id %}">{{ review.wine.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Dersi Değerlendir {{ review.rating }} of 5 by
	<a href="{% url 'reviews:user_review_list' review.user_name %}">
		{{ review.user_name }}
	</a>
</h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'base.html' %}

{% block title %}
<h2 class="text-center" id="navMargin">En Son Yorumlananlar</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4 col-md-4" style="padding: 30px 0 10px 0; height: 200px;">
        <div class="col-md-3 col-md-offset-1 col-xs-5 col-xs-offset-1 col-lg-3 col-lg-offset-1">
          {% if temp1 == review.wine.poster_path or temp2 == review.wine.poster_path %}
            {% load static %}
            <img class="img-thumbnail img-responsive" src="{% static '/download.png' %}" alt="image" style="height: 60px">
          {% else %}
            <img class="img-thumbnail img-responsive" src="{{ review.wine.poster_path }}">
          {% endif %}
        </div>
        <div class="col-xs-6 col-lg-6 col-md-6" style="padding: 0;">
            <h4><a href="{% url 'reviews:review_detail' review.id %}">
            {{ review.wine.name }}
            </a></h4>
            <h6 style="margin: 0;">rated {{ review.rating }} of 5 by 
            	<a href="{% url 'reviews:user_review_list' review.user_name %}">
            		{{ review.user_name }}
            	</a>
            </h6>
            <blockquote><p class="text-muted"><small>{{ review.comment }}</small></p></blockquote>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>Henüz yorumlanan içerik yok</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/user_recommendation_list.html
{% extends 'reviews/wine_list.html' %}

{% block title %}
{% if error %}
<div class="alert alert-warning" style="padding-top: 50px; font-size: 14px;">
 	<p class="lead"><strong>Uyarı</strong> {{ error }}</p>
</div>
{% endif %}
<h2 class="text-center" id="navMargin">Bu dersleri de izleyebilirsiniz {{ username }}</h2>
{% endblock %}

reviews/templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}
{% block title %}

<h2 class="text-center" id="navMargin"> {{ username }} tarafından değerlendirildi</h2>

{% endblock %}

reviews/templates/reviews/wine_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}

<script type="text/javascript">
    $(window).on('load', function() {      //Do the code in the {}s when the window has loaded 
        $("#loader").fadeOut("fast");  //Fade out the #loader div
    });
</script>

<div id="loader">
    <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%">
            <span class="sr-only">% 70 tamamlandı.</span>
        </div>
    </div>
</div>

<div class="row" style="border-bottom: 2px solid #ccc; padding-bottom: 30px; padding-top: 50px;" id="center-text">
    <div class="text-center col-md-6 col-xs-12 col-lg-6" id="img-tile">
        {% if temp1 == wine.poster_path or temp2 == wine.poster_path %}
            {% load static %}
            <img class="img-thumbnail img-responsive" src="{% static '/download.png' %}" alt="image" style="height: 60%">
        {% else %}
            <img class="img-responsive img-fluid img-thumbnail" src="{{ wine.poster_path }}" alt="image not found" style="height: 90%; width: 50%">
        {% endif %}
    </div>
    <div class="col-md-6 col-xs-12 col-lg-6">
        <h2 class="text-uppercase">{{ wine.name }}</h2>
        <h4><u><i><b>İlgili Disiplinler</b></i></u>: |{{ wine.genres }}</h4>
        <h4>Yorum Sayısı: {{ wine.review_set.count }} | Ortalama Puan: {{ wine.average_rating | floatformat }}</h4>
        {% if temp1 == movie_info.YouTube_URL %}
            <h4 class="alert alert-warning" id="trailer_borders">İçerik bulunamadı</h4>
        {% else %}
            <a href="{{ movie_info.YouTube_URL }}" target="_blank">
                <h4 class="alert alert-success" id="trailer_borders">{{ wine.name }} Derse gitmek için tıklayın.</h4>
            </a>
        {% endif %}
    </div>
</div>
<div class="row" style="border-bottom: 2px solid #ccc; padding: 20px;" id="fontSize">
    <p class="text-justify lead"><u><b><i>Özet</i></b></u>: {{ movie_info.overview }}</p>
</div>

{% endblock %}

{% block content %}

<h2 class="text-center">Değerlendir</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if user_name in wine.review_set.all.user_name %}
    <p><strong>Daha önce değerlendirdiniz. Yeniden değerlendirmek ister misiniz?</strong></p>
{% endif %}

<form class="text-center" style="padding: 20px 0" action="{% url 'reviews:add_review' wine.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Puanla
    </button>
    {% endbuttons %}
</form>

<h3 class="text-center" style="border-top: 2px solid #bbb; padding: 40px 0">Geçmiş Değerlendirmeleriniz</h3>

{% if wine.review_set.all %}
<div class="row text-center" style="padding-bottom: 30px">
    {% for review in wine.review_set.all|dictsortreversed:"pub_date" %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>

    {% endfor %}
</div>

{% else %}
<p>Bu ders için henüz bir değerlendirme yapılmamıştır.</p>
{% endif %}

{% endblock %}