reviews/urls.py
from django.conf.urls import url

from . import views

app_name = 'reviews'

urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url(r'^wine$', views.wine_list, name='wine_list'),
    # ex: /wine/5/
    url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    url(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    # ex: /review/user - get reviews for the logged user
    url(r'^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    # ex: /review/user - get reviews for the user passed in the url
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    # ex: /recommendation - get wine recommendations for the logged user
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
    url(r'^ncf_recommendation/$', views.ncf_users_recommendation_list, name='ncf_users_recommendation_list'),
    # ex: /about
    url(r'^about/$', views.about, name='about')
]

winerama/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include(('reviews.urls', 'reviews'), namespace="reviews")),
    url(r'^reviews/', include(('reviews.urls', 'reviews'), namespace="reviews")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    # imported all the mappings from django.contrib.auth.urls
    url(r'^accounts/', include(('django.contrib.auth.urls', 'auth'), namespace="auth")),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}

    <!-- jQuery library -->
    <script src="{% static '/script/jquery-3.3.1.min.js' %}" type="text/javascript">
    </script>

    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {% block bootstrap3_content %}

    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}" />
    <title>Akıllı Öğrenme Platformu</title>
</head>
<body>
<div class="container" style="background-color: #efefef;">
    <nav class="navbar navbar-fixed-top navbar-default navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Navigasyon Bölümü</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'reviews:review_list' %}">
                    <img class="img-responsive" src="{% static '/pencil.png' %}" alt="@" style="height: 100%; float: left; padding-right: 5px;">
                    <span>Ders Önerileri</span>
                </a>
            </div>
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'reviews:wine_list' %}">Dersler</a></li>
                    <li><a href="{% url 'reviews:review_list' %}">Ana Sayfa</a></li>
                    <li><a href="{% url 'reviews:about' %}">Hakkımızda</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">

                <!--Kullanıcı oturum açtığında, çıkış düğmesini ve tersi gösterir.-->
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'reviews:user_review_list' user.username %}">{{ user.username }}</a></li>
                    <!--Menü çubuğuna bir bağlantı ekleyelim; böylece oturum açmış bir kullanıcı önerilerine gidebilir.-->
                    <li><a href="{% url 'reviews:user_recommendation_list' %}">Sizin İçin Öneriler</a></li>
                    <li><a href="{% url 'reviews:ncf_users_recommendation_list' %}">En Popüler Dersler</a></li>
                    <li><a href="{% url 'auth:logout' %}">Çıkış</a></li>
                    {% else %}
                    <li><a href="{% url 'auth:login' %}">Giriş</a></li>
                    <li><a href="/accounts/register">Kayıt</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

<div class="footer navbar-fixed-bottom">
    <p class="text-center" style="color: #666666;">
        <span style=" background-color: #efefef; padding: 5px;">© 2019 Copyright: <a href="" target="_blank" class="text-warning">@Sadık Kırış</a>
        </span>
    </p>
</div>

</body>
</html>